//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GTnewsManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Menu2
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Menu2()
        {
            this.Event = new HashSet<Event>();
            this.Question = new HashSet<Question>();
        }
    
        public int menu2_id { get; set; }
        public int menu_id { get; set; }
        public string menu2_CNtext { get; set; }
        public string menu2_TWtext { get; set; }
        public string menu2_url { get; set; }
        public byte menu2_sort { get; set; }
        public bool menu2_status { get; set; }
        public byte menu2_type { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Event> Event { get; set; }
        public virtual Menu Menu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Question> Question { get; set; }
    }
}
